### ISSUE TITLE
Unhandled exception when using uBlock cookie filters

### ISSUE THREAD

**Issue by danielchalmers** [BytexDigital/BytexDigital.Blazor.Components.CookieConsent#32] opened 2024-06-29 18:18 UTC
Loading mudblazor.com in incognito with uBlock cookie filters enabled on the latest version results in the site getting stuck on the loading screen with these errors:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
dotnet.js:3 
        
        
        Uncaught (in promise) TypeError: Failed to fetch
    at Object.A [as fetch_like] (dotnet.js:3:4508)
    at dotnet.js:3:11593
    at dotnet.js:3:11609
blazor.webassembly.js:1  Error in mono_download_assets: Error: download 'https://mudblazor.com/_framework/BytexDigital.Blazor.Components.CookieConsent.wasm' for BytexDigital.Blazor.Components.CookieConsent.wasm failed 0 TypeError: Failed to fetch
Dt @ blazor.webassembly.js:1
3dotnet.js:3  Uncaught (in promise) Error: download 'https://mudblazor.com/_framework/BytexDigital.Blazor.Components.CookieConsent.wasm' for BytexDigital.Blazor.Components.CookieConsent.wasm failed 0 TypeError: Failed to fetch
    at dotnet.js:3:9983
    at async K (dotnet.js:3:8871)
    at async Y (dotnet.js:3:8196)
2mudblazor.com/:1  Uncaught (in promise) Error: download 'https://mudblazor.com/_framework/BytexDigital.Blazor.Components.CookieConsent.wasm' for BytexDigital.Blazor.Components.CookieConsent.wasm failed 0 TypeError: Failed to fetch
    at dotnet.js:3:9983
    at async K (dotnet.js:3:8871)
    at async Y (dotnet.js:3:8196)
blazor.webassembly.js:1  Uncaught (in promise) Error: Failed to start platform. Reason: Error: download 'https://mudblazor.com/_framework/BytexDigital.Blazor.Components.CookieConsent.wasm' for BytexDigital.Blazor.Components.CookieConsent.wasm failed 0 TypeError: Failed to fetch
    at mn (blazor.webassembly.js:1:57654)
dotnet.runtime.8.0.6.scyrrn9hx4.js:3  Uncaught (in promise) Error: download 'https://mudblazor.com/_framework/BytexDigital.Blazor.Components.CookieConsent.wasm' for BytexDigital.Blazor.Components.CookieConsent.wasm failed 0 TypeError: Failed to fetch
    at dotnet.js:3:9983
    at async K (dotnet.js:3:8871)
    at async Y (dotnet.js:3:8196)
```

If I disable the adblock, load the site successfully, then turn it back on, I get this error:

```
blazor.webassembly.js:1 
 
 GET https://mudblazor.com/_content/BytexDigital.Blazor.Components.CookieConsent/cookieconsent.js net::ERR_BLOCKED_BY_CLIENT
dotnet.runtime.8.0.6.scyrrn9hx4.js:3 
 fail: BytexDigital.Blazor.Components.CookieConsent.CookieConsentService[0]
      Exception raised trying to run CookiePreferencesChanged event handler
Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://mudblazor.com/_content/BytexDigital.Blazor.Components.CookieConsent/cookieconsent.js
TypeError: Failed to fetch dynamically imported module: https://mudblazor.com/_content/BytexDigital.Blazor.Components.CookieConsent/cookieconsent.js
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.PublishToJsAsync(String name, String data)
   at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.BroadcastCookiePreferencesChangedAsync(CookiePreferences cookiePreferences)
   at BytexDigital.Blazor.Components.CookieConsent.CookieConsentService.PublishCookiePreferencesChanged(CookiePreferences preferences)
   at BytexDigital.Blazor.Components.CookieConsent.CookieConsentServiceAuthority.NotifyApplicationLoadedAsync()
```

but the site still loads ok.

- EasyList/uBO – Cookie Notices
- AdGuard/uBO – Cookie Notices

I'm looking to be able to take them blocking the cookies as a denial and continue loading the site smoothly.

**Comment by danielchalmers** [comment] 2024-06-29 18:20
I don't think we're using the code wrong but we might have missed something https://github.com/search?q=repo%3AMudBlazor%2FMudBlazor%20cookie&type=code

**Comment by ScarletKuro** [comment] 2024-06-29 19:19
> I don't think we're using the code wrong but we might have missed something https://github.com/search?q=repo%3AMudBlazor%2FMudBlazor%20cookie&type=code

Better to redirect to PR that introduced it: https://github.com/MudBlazor/MudBlazor/pull/8602

**Comment by RyanTT** [comment] 2024-06-30 01:05
https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/pull/31 would atleast fix the .js file from not being loaded, but the .wasm file is a bit tricky to me at the moment, as it gets baked into the bootup process of the WASM environment and I'm not sure yet how to best combat the blocking of this file crashing the entire bootup process. I'll look around a little

**Comment by ScarletKuro** [comment] 2024-06-30 09:48
> #31 would atleast fix the .js file from not being loaded, but the .wasm file is a bit tricky to me at the moment, as it gets baked into the bootup process of the WASM environment and I'm not sure yet how to best combat the blocking of this file crashing the entire bootup. I'll look around a little

As far as I read about the `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` error on StackOverflow, it seems like the adblocker is blocking URLs that contain "cookieconsent" or similar terms. While issue #31 can deal with the JS block since you can customize that part, there is nothing you can do about the assembly name.

It's not really impossible to dynamically load an assembly in WASM, but it is not trivial, especially if you need to rename the original assembly. Furthermore, it is impossible to dynamically load it if you are using `WasmEnableWebcil` since, as far as I know, the `AssemblyLoadContext` doesn't support it (though I am uncertain about this, as I recall some complaints about it in the runtime repository). At this point, it would be easier to fork the library and apply the `AssemblyName` change in the `csproj`.

**Comment by RyanTT** [comment] 2024-07-21 16:53
It would be interesting to know how common it is for people to be running an adblocker configured to intercept anything with the word cookie in it. If it's a reasonable amount, we could just change the assembly name here in the repo, I don't see any reason as to why not to do it. Maybe something still recognizable such as BytexDigital.Blazor.Components.CC?

**Comment by ScarletKuro** [comment] 2024-07-21 17:11
I have AdGuard on my PC, and I just tried to install an "AdGuard Cookie Notice filter," but it gave the following error:
![filter](https://github.com/user-attachments/assets/ea3466c8-4e7e-4fe2-9ead-57650be201fd)

However, this filter is **not official**; it’s a third-party filter that hasn't been updated since 2023. Is there anything to worry about? I would worry if it was a a supported feature in the AdGuard, but it's not the case.

**Comment by danielchalmers** [comment] 2024-07-21 17:14
It's caused by one of the two default cookie lists in uBlock so very easy to enable.

**Comment by danielchalmers** [comment] 2024-07-21 17:29
The problem of changing the name (`BytexDigital.Blazor.Components.CC`) is how trivial it is to add it back to the list like a game of cat and mouse.

**Comment by ScarletKuro** [comment] 2024-07-21 17:34
> The problem of changing the name (`BytexDigital.Blazor.Components.CC`) is how trivial it is to add it back to the list like a game of cat and mouse.

This just means there is nothing much the library author can do except the one js part that was already addressed via https://github.com/BytexDigital/BytexDigital.Blazor.Components.CookieConsent/pull/31

**Comment by RyanTT** [comment] 2024-07-21 17:35
The change in assembly name would atleast allow the app to still load, albeit the cookie consent parts entirely not working, but that is more in line with what such a user would want than the app itself not loading in it's entirety I suppose

**Comment by RyanTT** [comment] 2024-07-21 17:42
Going it over it now, this would sadly mean a new nuget package name aswell as some changes required in the readme file as e.g. path of the css would also be different

**Comment by danielchalmers** [comment] 2024-07-21 17:44
Should this be escalated to the ASP.NET team?

**Comment by RyanTT** [comment] 2024-07-21 17:50
It does seem like something they should look at at some point, but my hopes of them finding a good solution to this are pretty slim admittedly :D I could atleast build and publish a second version of the package with CookieConsent shortened to CC for now. That would make it simple to pick that package if you fear running into issues with this. Would probably make sense to apply the same to the Google Analytics library of ours then.

**Comment by ScarletKuro** [comment] 2024-07-21 18:02
> this would sadly mean a new nuget package name aswell

I think you can have do this:
```
<PackageId>BytexDigital.Blazor.Components.CookieConsent</PackageId>
<AssemblyName>RandonName</AssemblyName>
```
But you do need to adjust the `IJSObjectReference` part. Probably would be a good thing to see how well this does in WASM

**Comment by RyanTT** [comment] 2024-07-21 18:21
Hm, it appears with the package ID set to the original name but the assembly renamed, publishing to nuget works correctly, but once included in a project, the correct paths to the wwwroot files is CookieConsent and not CC like the assembly's name

**Comment by ScarletKuro** [comment] 2024-07-21 18:39
> Hm, it appears with the package ID set to the original name but the assembly renamed, publishing to nuget works correctly, but once included in a project, the correct paths to the wwwroot files is CookieConsent and not CC like the assembly's name

That's interesting and very unfortunate

**Comment by RyanTT** [comment] 2024-07-21 18:40
Well, good news: It does work as intended for the most part. The wasm file downloaded is now called BytexDigital.Blazor.Components.CC, so it shouldn't be blocked anymore by a regex that searches for urls. The JS will still be blocked by AdBlock, but the app should still start.

Could you run a test on your end with this preview release?

https://www.nuget.org/packages/BytexDigital.Blazor.Components.CookieConsent/1.2.0-preview.1721587026

**Comment by ScarletKuro** [comment] 2024-07-21 20:22
I made this PR https://github.com/MudBlazor/MudBlazor/pull/9471
Can you test it @danielchalmers  with your uBlock. It works fine for me.

**Comment by ScarletKuro** [comment] 2024-07-21 20:34
There is some exception that is not related to this topic but 
```
invoke-js.ts:176  fail: BytexDigital.Blazor.Components.CookieConsent.CookieConsentService[0]
      Exception raised trying to run CookiePreferencesChanged event handler
Microsoft.JSInterop.JSException: Could not find 'CookieConsent.BroadcastEvent' ('CookieConsent' was undefined).
Error: Could not find 'CookieConsent.BroadcastEvent' ('CookieConsent' was undefined).
    at https://localhost:5001/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:336)
    at w (https://localhost:5001/_framework/blazor.webassembly.js:1:5079)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (https://localhost:5001/_framework/blazor.webassembly.js:1:58849)
    at https://localhost:5001/_framework/dotnet.runtime.8.0.7.urcsr75yt5.js:3:178364
    at Tl (https://localhost:5001/_framework/dotnet.runtime.8.0.7.urcsr75yt5.js:3:179198)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BytexDigital.Blazor.Components.CookieConsent.Interop.CookieConsentInterop.BroadcastEventAsync(Boolean isDirectedTowardsWasm, String name, String data)
   at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.PublishToJsAsync(String name, String data)
   at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.BroadcastCookiePreferencesChangedAsync(CookiePreferences cookiePreferences)
   at BytexDigital.Blazor.Components.CookieConsent.CookieConsentService.PublishCookiePreferencesChanged(CookiePreferences preferences)
   at BytexDigital.Blazor.Components.CookieConsent.CookieConsentServiceAuthority.NotifyApplicationLoadedAsync()
```
When I disabled `ImportJsAutomatically` and added the script to `docs.js`. I'm not yet sure why it appears.

**Comment by ScarletKuro** [comment] 2024-07-21 22:10
> There is some exception that is not related to this topic but related to #31
> 
> ```
> invoke-js.ts:176  fail: BytexDigital.Blazor.Components.CookieConsent.CookieConsentService[0]
>       Exception raised trying to run CookiePreferencesChanged event handler
> Microsoft.JSInterop.JSException: Could not find 'CookieConsent.BroadcastEvent' ('CookieConsent' was undefined).
> Error: Could not find 'CookieConsent.BroadcastEvent' ('CookieConsent' was undefined).
>     at https://localhost:5001/_framework/blazor.webassembly.js:1:368
>     at Array.forEach (<anonymous>)
>     at l.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:336)
>     at w (https://localhost:5001/_framework/blazor.webassembly.js:1:5079)
>     at https://localhost:5001/_framework/blazor.webassembly.js:1:2872
>     at new Promise (<anonymous>)
>     at b.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:2835)
>     at Object.vn [as invokeJSJson] (https://localhost:5001/_framework/blazor.webassembly.js:1:58849)
>     at https://localhost:5001/_framework/dotnet.runtime.8.0.7.urcsr75yt5.js:3:178364
>     at Tl (https://localhost:5001/_framework/dotnet.runtime.8.0.7.urcsr75yt5.js:3:179198)
>    at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
>    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
>    at BytexDigital.Blazor.Components.CookieConsent.Interop.CookieConsentInterop.BroadcastEventAsync(Boolean isDirectedTowardsWasm, String name, String data)
>    at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.PublishToJsAsync(String name, String data)
>    at BytexDigital.Blazor.Components.CookieConsent.Broadcasting.CookieConsentEventHandler.BroadcastCookiePreferencesChangedAsync(CookiePreferences cookiePreferences)
>    at BytexDigital.Blazor.Components.CookieConsent.CookieConsentService.PublishCookiePreferencesChanged(CookiePreferences preferences)
>    at BytexDigital.Blazor.Components.CookieConsent.CookieConsentServiceAuthority.NotifyApplicationLoadedAsync()
> ```
> 
> When I disabled `ImportJsAutomatically` and added the script to `docs.js`. I'm not yet sure why it appears. When I type `CookieConsent.BroadcastEvent` in console it definitely exist: ![error](https://private-user-images.githubusercontent.com/19953225/350795298-74a82ce1-cfda-4b6b-bf98-cecff9bc2875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDAwODIsIm5iZiI6MTcyMTU5OTc4MiwicGF0aCI6Ii8xOTk1MzIyNS8zNTA3OTUyOTgtNzRhODJjZTEtY2ZkYS00YjZiLWJmOTgtY2VjZmY5YmMyODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDIyMDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZDgxOTc1OWUyMGNmZDJhYjMxN2M0MjlmMzdiZjljZDExMmI4MWU1ZTExOGI1ZjkwMmNjMWFiYTE2ZWY4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pG5VUJvl-GyiSDpkjRL5YH12a5vQl3D3yZM9RkCPpcc)

Nvm, false alarm. It's just my poor JS knowledge. I forgot to add `window.CookieConsent`.

**Comment by ScarletKuro** [comment] 2024-07-23 20:25
FYI: https://github.com/MudBlazor/MudBlazor/pull/9471 is merged and is in production https://mudblazor.com/

**Closed** 2024-08-15 01:14 UTC
